// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APINetCore.Models;

public partial class aspnet_Users
{
    public Guid ApplicationId { get; set; }

    public Guid UserId { get; set; }

    public string UserName { get; set; }

    public string LoweredUserName { get; set; }

    public string MobileAlias { get; set; }

    public bool IsAnonymous { get; set; }

    public DateTime LastActivityDate { get; set; }

    public string Name { get; set; }

    public string LastName { get; set; }

    public bool FirstTimeChangedPassword { get; set; }

    public virtual aspnet_Membership aspnet_Membership { get; set; }
}