// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APINetCore.Models;

public partial class cat_maritimeshippers
{
    public long MaritimeShippersId { get; set; }

    public string MaritimeShippersDescription { get; set; }

    public Guid? UserName { get; set; }

    public DateTime? FechaAlta { get; set; }

    public Guid? UserNameActualizo { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public bool? EsActivo { get; set; }

    public long? FinanzasSAPId { get; set; }

    public bool? EsMaritimo { get; set; }

    public string email { get; set; }

    public bool? EsInterpacifico { get; set; }

    public bool? EsCrossborder { get; set; }

    public long? OperacionesSAPId { get; set; }

    public long? MyRSAPId { get; set; }

    public bool? FreePool { get; set; }

    public bool? Desconsolidar { get; set; }

    public bool? EsPatioRevenu { get; set; }

    public bool? EsRemolque { get; set; }

    public bool? EsRemolqueCrossBorder { get; set; }

    public bool? Notificacion24HCrossBorder { get; set; }

    public long? ATRSAPID { get; set; }

    public string MYRemail { get; set; }
}