// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APINetCore.Models;

public partial class Imex_Chassis
{
    public int ChassisId { get; set; }

    public string Chassis { get; set; }
}